version: '3'
services:
  # PostgreSQL
  sns_dev:
    image: postgres:12
    env_file: ./DRF/docker.env
    volumes:
      - sns_dev_data:/var/lib/postgresql/data
    networks:
      - backend_network
 
  # Django REST framework
  drf:
    container_name: drf
    build: ./DRF
    command: python manage.py runserver drf:8000
    volumes:
      - ./drf-volume:/code
    depends_on:
      - sns_dev
    networks:
      - backend_network
  nginx:
    container_name: nginx
    build: ./Nginx
    ports:
      - "80:80"
    networks:
      - backend_network
    depends_on:
      - drf 

networks:
  backend_network:
    driver: bridge
volumes:
  sns_dev_data: